// Link: https://cses.fi/problemset/task/1149

#include <iostream>
#include <string>
#include <vector>

using namespace std;
// we are generating all distinct subsequences of a string, and counting them modulo 1e9+7
// we can use a dp approach where dp[i] is the number of distinct subsequences using the first i characters of the string
// to calculate dp[i], we can double the number of choices from dp[i-1]
// however, if the current character has been seen before, we need to subtract the duplicates that were generated by the previous occurrence of this character
// we can keep track of the last occurrence of each character to efficiently handle the duplicates

int main() {
    // Optimize standard I/O operations
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);

    string s;
    if (!(cin >> s)) return 0;

    int n = s.length();
    long long MOD = 1e9 + 7;

    // dp[i] stores the number of distinct subsequences using the first i characters
    vector<long long> dp(n + 1, 0);
    dp[0] = 1; // Base case: the empty string ""

    // last[ch] stores the 1-based index of the last occurrence of character ch
    vector<int> last(26, 0);

    for (int i = 1; i <= n; i++) {
        char ch = s[i - 1];
        int ch_idx = ch - 'a';

        // Rule 1: Double the number of current choices
        dp[i] = (2 * dp[i - 1]) % MOD;

        // Rule 2: If seen before, subtract the duplicates
        if (last[ch_idx] != 0) {
            int prev_idx = last[ch_idx];
            dp[i] = (dp[i] - dp[prev_idx - 1] + MOD) % MOD;
        }

        // Record the current 1-based index as the most recent sighting
        last[ch_idx] = i;
    }

    // Subtract 1 to exclude the empty string from the final generated count
    long long ans = (dp[n] - 1 + MOD) % MOD;
    
    cout << ans << "\n";

    return 0;
}